export const emailConstants = {
  EMAIL_VERIFIKASI_URL: process.env.REACT_APP_URL_WEBAPP + '/#USER_TYPE#/activate/#REG_ID#?user=#EMAIL#',
  EMAIL_VERIFIKASI_AKUN: {
    SUBJECT: "Verifikasi Akun",
    MESSAGE: "<html><head><link href=\"https://cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.css\" rel=\"stylesheet\"><style>.logo{margin-bottom:.7rem}.verify__wrap{text-align:center}.verify__title{font-weight:700;font-size:2rem}.verify__link{font-weight:700;text-decoration:underline}</style></head><body><div><div class=\"verify__wrap\"><img class=\"logo\" src=\"https://storage.googleapis.com/artifacts.concrete-plasma-244309.appspot.com/homespot/logo/logo.svg\"><h1 class=\"verify__title\">Verifikasi Email Kamu</h1><p>Data registrasi kamu telah berhasil kami terima. Verifikasi email kamu dengan mengklik tautan di bawah ini:</p><p class=\"verify__link\"><a href=\"#EMAIL_VERIFIKASI_URL#\">Verifikasi Email</a></p><p>Atau kamu dapat menyalin link berikut untuk memverifikasi email kamu</p><p class=\"verify__link\"><a href=\"#EMAIL_VERIFIKASI_URL_2#\">#DISPLAY_EMAIL_VERIFIKASI_URL#</a></p></div></div></body></html>"
  },
  EMAIL_VERIFIKASI_AKUN_SUKSES: {
    SUBJECT: "Verifikasi Akun Sukses",
    MESSAGE: "<html><head><style>.doneRegis__title{font-weight:700;font-size:2rem}.doneRegis__ifAsk{text-align:center;margin-top:2rem}.doneRegis__conWrap{padding:.2rem;background:#ebebeb;text-align:center;align-items:center}.doneRegis__tblWrap{margin:0 auto;text-align:center}.doneRegis__tblTxt{margin-top:0;margin-bottom:0;font-weight:400}</style></head><body><div><h1 class=\"doneRegis__title\">Registrasi Kamu Berhasil</h1><p>Selamat <b>#NAMA_LENGKAP#</b>, Kamu bisa mencari dan membeli rumah idamanmu melalui Homespot</p><p class=\"doneRegis__ifAsk\">Bila ada pertanyaan, Silahkan menghubungi kami :</p><div class=\"doneRegis__conWrap\"><table class=\"doneRegis__tblWrap\"><tr><th><img src=\"https://storage.googleapis.com/artifacts.concrete-plasma-244309.appspot.com/homespot/wa-tiny.png\" alt=\"wa-tiny-icon\"></th><th><p class=\"doneRegis__tblTxt\">+622150864230</p></th></tr></table><table class=\"doneRegis__tblWrap\"><tr><th><img src=\"https://storage.googleapis.com/artifacts.concrete-plasma-244309.appspot.com/homespot/email-tiny.png\" alt=\"email-tiny-icon\"></th><th><p class=\"doneRegis__tblTxt\">support@homespot.co.id</p></th></tr></table></div></div></body></html>"
  }
};