export const SHOW_MODAL_REGISTER = "SHOW_MODAL_REGISTER";
export const SHOW_MODAL_LOGIN = "SHOW_MODAL_LOGIN";
export const SHOW_SINGLE_MODAL = "SHOW_SINGLE_MODAL";
export const SHOW_MODAL_RATING = "SHOW_MODAL_RATING";
export const SHOW_MODAL_FILTER = "SHOW_MODAL_FILTER";
export const SHOW_LINK_MODAL = "SHOW_LINK_MODAL";
export const SHOW_RINGKASAN_BUYER = "SHOW_RINGKASAN_BUYER";
export const SHOW_METHOD_PAYMENT_MODAL = "SHOW_METHOD_PAYMENT_MODAL";
export const SHOW_USER_PAYMENT_MODAL = "SHOW_USER_PAYMENT_MODAL";
export const SHOW_BRIVA_MODAL = "SHOW_BRIVA_MODAL";
export const SHOW_APPROVAL_KPR_MODAL = "SHOW_APPROVAL_KPR_MODAL";
export const SHOW_SUCCESS_SELL = "SHOW_SUCCESS_SELL";
export const SHOW_SELECT_QUESTION = "SHOW_SELECT_QUESTION";
export const SHOW_CHAT = "SHOW_CHAT";
export const SHOW_CONF_LOGOUT = "SHOW_CONF_LOGOUT";

export const LOADING = "LOADING";
export const INPUT_OTP = "INPUT_OTP";
export const SHOW_DETAIL_FROM_MAPS = "SHOW_DETAIL_FROM_MAPS";

export const SELECTED_PIC1 = "SELECTED_PIC1";
export const SELECTED_PIC2 = "SELECTED_PIC2";

export const SELECTED_SELL_BUY = "SELECTED_SELL_BUY";
export const SELECTED_PRICE = "SELECTED_PRICE";
export const SELECTED_PROPERTY_TYPE = "SELECTED_PROPERTY_TYPE";
export const SELECTED_BEDROOM = "SELECTED_BEDROOM";
export const SELECTED_BATHROOM = "SELECTED_BATHROOM";
export const SELECTED_FILTER = "SELECTED_FILTER";
export const SELECTED_GARAGE_CAR = "SELECTED_GARAGE_CAR";

export const SELECTED_CURRENCY = "SELECTED_CURRENCY";
export const SELECTED_PERIOD = "SELECTED_PERIOD";

export const SET_DOB = "SET_DOB";
export const SET_GENDER = "SET_GENDER";
export const SET_MARTIAL_STATUS = "SET_MARTIAL_STATUS";
export const SET_UANG_TANGGUNGAN = "SET_UANG_TANGGUNGAN";
export const SET_JANGKA_PERLINDUNGAN = "SET_JANGKA_PERLINDUNGAN";

export const SET_CASH_SUBMISSION = "SET_CASH_SUBMISSION";
export const SET_KPR_SUBMISSION = "SET_KPR_SUBMISSION";
export const SET_KPR_BRISYARIAH = "SET_KPR_BRISYARIAH";
export const SET_KPR_BRI = "SET_KPR_BRI";
export const SET_SELLPROPS_TYPEOFPROPERTY = "SET_SELLPROPS_TYPEOFPROPERTY";
export const SET_SELLPROPS_PROPERTYTYPE = "SET_SELLPROPS_PROPERTYTYPE";
export const SET_FILTER_TYPEOFPROPERTY = "SET_FILTER_TYPEOFPROPERTY";
export const SET_FILTER_PROPERTYTYPE = "SET_FILTER_PROPERTYTYPE";
export const SET_QUESTION_BEFORE_CHAT = "SET_QUESTION_BEFORE_CHAT";

export const SET_JENIS_SUKU_BUNGA = "SET_JENIS_SUKU_BUNGA";
export const SET_JENIS_SUBSIDI = "SET_SUBSIDI";
export const SET_FIXED_CREDIT = "SET_FIXED_CREDIT";

export const SET_MIN_PRICE = "SET_MIN_PRICE";
export const SET_MAX_PRICE = "SET_MAX_PRICE";

export const SET_LOGGED_IN = "SET_LOGGED_IN";

export const SET_CERTIFICATE = "SET_CERTIFICATE";
export const SET_NUMBER_OF_FLOORS = "SET_NUMBER_OF_FLOORS";
export const SET_PROPERTY_CONDITION = "SET_PROPERTY_CONDITION";
export const SET_ELECTRICAL_POWER = "SET_ELECTRICAL_POWER";
export const SET_FACING_HOUSE = "SET_FACING_HOUSE";
export const SET_YEAR_OF_DEVELOPMENT = "SET_YEAR_OF_DEVELOPMENT";
export const SET_MAID_ROOM = "SET_MAID_ROOM";

//for fetching data
export const TEST_FETCH_MOVIE = "TEST_FETCH_MOVIE";
export const FETCH_USER_LOGIN = "FETCH_USER_LOGIN";
export const SUCCESS_REG = "SUCCESS_REG";
export const INPUT_USER_REG = "INPUT_USER_REG";
export const EMAIL_RESET_PASS = "EMAIL_RESET_PASS";
export const LOADING_ACTIVATION = "LOADING_ACTIVATION";
export const FAILED_REGLOGIN = "FAILED_REGLOGIN";
export const REDIRECT_LOGIN = "REDIRECT_LOGIN";
export const FETCH_LOGOUT = "FETCH_LOGOUT";
export const RESET_STATE_LOGIN = "RESET_STATE_LOGIN";
export const RESET_LOADING = "RESET_LOADING";
export const DEV_NAME = "DEV_NAME";
export const INQUIRY_DATI2 = "INQUIRY_DATI2";
export const INQUIRY_DETAIL_PROPS = "INQUIRY_DETAIL_PROPS";

export const SA_SUCCESS = "SA_SUCCESS";
export const SA_SUCCESSPENGAJUAN = "SA_SUCCESSPENGAJUAN";
export const SA_SUCCESSREGISTERV2 = "SA_SUCCESSREGISTERV2";
export const SA_SUCCESSINPUTREGISTER = "SA_SUCCESSINPUTREGISTER";
export const SA_FAIL = "SA_FAIL";
export const SA_REDIRECT = "SA_REDIRECT";
export const SA_RESET = "SA_RESET";
export const SA_RESAPI = "SA_RESAPI";
export const SA_EDIT = "SA_EDIT";
export const SA_EDIT_MODE = "SA_EDIT_MODE";

export const FS_LOADING = "FS_LOADING";
export const UPLOAD_FILE = "UPLOAD_FILE";

export const FILTER_SEARCH = "FILTER_SEARCH";
export const FILTER_SALES_PROJECT = "FILTER_SALES_PROJECT";
export const SET_LONGLAT = "SET_LONGLAT";

export const SHOW_ADM_MENU = "SHOW_ADM_MENU";

export const PRJ_INFO = "PRJ_INFO";
export const PRJ_CLS_INFO_DTO = "PRJ_CLS_INFO_DTO";
export const PRJ_PROPERTI = "PRJ_PROPERTI";
export const STEPPER_TAB_INDEX = "STEPPER_TAB_INDEX";
export const PRJ_PHOTO = "PRJ_PHOTO";
export const PRJ_PHOTO_INQUIRY = "PRJ_PHOTO_INQUIRY";
export const PRJ_ADDRESS = "PRJ_ADDRESS";
export const PRJ_BROCHURE = "PRJ_BROCHURE";
export const PRJ_SITEPLAN = "PRJ_SITEPLAN";
export const PRJ_PRICELIST = "PRJ_PRICELIST";
export const PRJ_GRUP_PROP = "PRJ_GRUP_PROP";
export const PRJ_ADDRESS_JSON = "PRJ_ADDRESS_JSON";
export const PRJ_RESET = "PRJ_RESET";
export const PRJ_SET_ID_PROP = "PRJ_SET_ID_PROP";
export const PRJ_SET_BROSUR_ID = "PRJ_SET_BROSUR_ID";
export const PRJ_SET_SITEPLAN_ID = "PRJ_SET_SITEPLAN_ID";
export const PRJ_SET_PRICELIST_ID = "PRJ_SET_PRICELIST_ID";
export const PRJ_SET_IMAGE_PRJ_ID = "PRJ_SET_IMAGE_PRJ_ID";
export const PRJ_SET_IMAGE_PROP_ID = "PRJ_SET_IMAGE_PROP_ID";
export const PRJ_IMAGE_PROP = "PRJ_IMAGE_PROP";
export const PRJ_IMAGE_PROP_INQUIRY = "PRJ_IMAGE_PROP_INQUIRY";
export const SET_WISHLIST = "SET_WISHLIST";
export const SET_ACTIVATION = "SET_ACTIVATION";
export const SET_MESSAGE_ERROR = "SET_MESSAGE_ERROR";

export const NEXT_PAGE = "NEXT_PAGE";
export const PREV_PAGE = "PREV_PAGE";
export const NEXT_PAGE_JUMPER = "NEXT_PAGE_JUMPER";
export const SET_PAGE_DATA = "SET_PAGE_DATA";
export const SET_PAGE_DATA_NEXT = "SET_PAGE_DATA_NEXT";
export const SET_PAGE_DATA_ERROR = "SET_PAGE_DATA_ERROR";
export const SET_PAGE_SEARCH = "SET_PAGE_SEARCH";
export const SET_NEXT_PAGE_LOADING = "SET_NEXT_PAGE_LOADING";
export const REMOVE_PAGINATION_DATA = "REMOVE_PAGINATION_DATA";
export const RESET_PAGINATION_PAGE = "RESET_PAGINATION_PAGE";
