import "./styles/index.scss";

//Packages
import "react-initials-avatar/lib/ReactInitialsAvatar.css";
import "rc-slider/assets/index.css";
import "react-awesome-lightbox/build/style.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import "./styles/react-slick-custom.scss";
import "react-tabs/style/react-tabs.css";
import 'react-tabs-scrollable/dist/rts.css'
import "./styles/rich-text-editor.scss"

// Components
import "./styles/components/dropdown.scss";
import "./styles/components/google-maps/marker.scss";
import "./styles/components/input/radio-button.scss";
import "./styles/components/input/disable-arrows-input-number.scss";
import "./styles/components/stepper/stepper.scss";
import "./styles/components/navbar/navbarUser.scss";
import "./styles/components/navbar/nav-header-admin.scss";
import "./styles/components/template/profile.scss";
import "./styles/components/popup/chat/select-question.scss";
import "./styles/components/popup/chat/chat.scss";
import "./styles/components/input/radiobox.scss";
import "./styles/components/button/save/save-love-and-share.scss";
import "./styles/components/button/button.scss";
import "./styles/components/input/textbox.scss";
import "./styles/components/footer/footer.scss";
import "./styles/components/text/text.scss";
import "./styles/components/text/field-personal-data.scss";
import "./styles/components/modal/payment-method.scss";
import "./styles/components/modal/kpr-submission.scss";
import "./styles/components/modal/filter-search.scss";
import "./styles/components/modal/cash-submission.scss";
import "./styles/components/modal/modal-sf.scss";
import "./styles/components/modal/confirm-btn.scss";
import "./styles/components/input/textbox-label.scss";
import "./styles/components/input/select/choose-payment-method.scss";
import "./styles/components/input/dropdown.scss";
import "./styles/components/input/dropdown-menu/slider.scss";
import "./styles/components/input/dropdown-menu/list.scss";
import "./styles/components/input/textbox-dropdown.scss";
import "./styles/components/input/upload/upload.scss";
import "./styles/components/input/textarea.scss";
import "./styles/components/input/checkbox.scss";
import "./styles/components/input/input-prefix.scss";
import "./styles/components/cards/search-result.scss";
import "./styles/components/images/small-images.scss";
import "./styles/components/line/border-line.scss";
import "./styles/components/tabs/tabs.scss";
import "./styles/components/organisms/sideMenu.scss";
import "./styles/components/tabs/tabs-profile.scss";
import "./styles/components/tables/table.scss";
import "./styles/components/tables/responsive-table.scss";
import "./styles/components/pagination/pagination.scss";
import "./styles/components/side-menu/sidemenu-admin.scss";
import "./styles/components/google-maps/google-maps.scss";
import "./styles/components/datepicker/DatePicker.scss";
import "./styles/components/modal/signup-login.scss";
import "./styles/pages/sell-property/v2/sell-property-v2.scss";
import "./styles/components/modal/v2/select-compare-prop.scss";

// Pages
import "./styles/pages/sell-property/sell-property.scss";
import "./styles/pages/product-details/product-details.scss";
import "./styles/pages/kpr/approval.scss";
import "./styles/pages/landing-page/landing-page.scss";
import "./styles/pages/forgot-otp.scss";
import "./styles/pages/search-results/search-results.scss";
import "./styles/pages/kpr/simulation.scss";
import "./styles/pages/profile/profile.scss";
import "./styles/pages/profile-sales/profile-sales.scss";
import "./styles/pages/admin/admin.scss";
import "./styles/pages/product-details/v2/compare-products.scss";
import "./styles/pages/project-details/project-details.scss";
import "./styles/pages/wishlist/wishlist.scss";
import "./styles/pages/admin-cabang/index.js";
import "./styles/pages/admin/dynamic-banner.scss";
